version: '3.3'
services:
    api:
        build:
          context: ./
          dockerfile: Dockerfile
        image: superdru:webchat_api
        links:
          - postgres
        depends_on:
          - "postgres"
          - "migrations"
        ports:
          - "5000:80"
        environment:    
            Database__ConnectionString: Host=postgres;Port=5432;Database=mydb;Username=mydb;Password=mydb
        networks:
          - aspnetcoreapp-network
      
    postgres:
        container_name: 'postgres'
        image: postgres:latest
        restart: always
        ports:
          - "5432"
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: mydb
            POSTGRES_PASSWORD: mydb
      
    migrations:
        build:
          context: .
          dockerfile: ./Migrations.Dockerfile
        image: migrations
        links:
          - "postgres"
        depends_on:
          - "postgres"
        environment:
          - loglevel=debug
          - username=mydb
          - password=mydb
          - dbname=mydb
          - host=postgres
          - port=5432